### PR TITLE
Fix "Latest release" at the bottom

### PR DESCRIPTION
**Pull request by l1ttleO**

### CODE REVIEW

**Comment by pop4959** [comment]
2.18.22 is not a release, it is an in-development build for 2.18.1. The latest release is 2.18.0. 😃

**Comment by l1ttleO** [comment]
I was thinking of putting `2.18.0` but then I thought that it isn't really the latest release so I changed it to `2.18.0.22`

**Comment by pop4959** [comment]
Just as a word of advice, generally follow the convention that prior contributors set in the code, unless you have an explicit reason why not to. So e.g., it was 2.17.2 before, so don't add an extra .x to the end. 😛

**Comment by l1ttleO** [comment]
I just thought that in case of `2.17.2` the `.x` isn't required because it's a 0 anyway, but here it's 22
My bad anyway, sorry.

**Comment by l1ttleO** [comment]
Closing because it looks like almost no one saw this

**Pull request closed without merging**
